name: Construction d'un projet

# on = déclachement d'un evenement
on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:
jobs:
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
      - name: create folder on remote vm
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 192.168.56.10
          username: vagrant
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            sudo mkdir -p /opt/applications/sa

  build:
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
    - name: Téléchargement des sources
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true -B package --file pom.xml

    - name: Rename Jar
      run: mv target/*.jar target/sa.jar

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 192.168.56.10
        username: vagrant
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        source: "target/sa.jar"
        target: /opt/applications/sa
        strip_components: 1

  run-jar:
    name: run-jar
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: create folder on remote vm
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 192.168.56.10
          username: vagrant
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            sudo ln -sf /opt/applications/sa/sa.jar /etc/init.d/sa
            sudo /etc/init.d/sa stop
            sudo /etc/init.d/sa start
